packages:
  - apps/*
  - packages/*
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  '@zvec/zvec': true
  electron: true
  electron-winstaller: false
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: true
  spawn-sync: true
  tesseract.js: false
